//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonImages
    {
        public int ImgId { get; set; }
        public string ImgUrl { get; set; }
        public string ImgName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> CommonId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> State { get; set; }
    }
}
