//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_Hotel
    {
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public Nullable<int> HotelType { get; set; }
        public string HotelThemeImage { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Start { get; set; }
        public Nullable<decimal> End { get; set; }
        public Nullable<int> DeskCount { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Label { get; set; }
        public string LabelContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Letter { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
