//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD_SaleSource
    {
        public int SourceId { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> SaleTypeId { get; set; }
        public Nullable<int> IsRebate { get; set; }
        public string SourceAddress { get; set; }
        public string CommoandName { get; set; }
        public string CommondPhone { get; set; }
        public string CommondBankName { get; set; }
        public string CommondBankCard { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Description { get; set; }
        public string letter { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
