//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Customer
    {
        public System.Guid CustomerID { get; set; }
        public string Bride { get; set; }
        public string BridePhone { get; set; }
        public string Groom { get; set; }
        public string GroomPhone { get; set; }
        public string Operator { get; set; }
        public string OperatorPhone { get; set; }
        public string ContactMan { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> PartyDate { get; set; }
        public string Hotel { get; set; }
        public string BanqueType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SaleType { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<int> DeskCount { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string ReCommand { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> IsVip { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsFinish { get; set; }
        public Nullable<int> EvalState { get; set; }
        public string Description { get; set; }
    }
}
