//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_InviteDetails
    {
        public int DetailsId { get; set; }
        public Nullable<int> InviteId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> InviteState { get; set; }
        public string StateName { get; set; }
        public string InviteContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> NextFollowDate { get; set; }
    }
}
