//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FL_Order()
        {
            this.FL_OrderDetails = new HashSet<FL_OrderDetails>();
        }
    
        public System.Guid OrderID { get; set; }
        public string OrderCoder { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.DateTime> ComeDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<int> FollowCount { get; set; }
        public Nullable<System.DateTime> LastFollowDate { get; set; }
        public Nullable<System.DateTime> NextFollowDate { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FL_OrderDetails> FL_OrderDetails { get; set; }
    }
}
