//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyMusic
    {
        public System.Guid MusicId { get; set; }
        public string MusicName { get; set; }
        public string MusicOtherName { get; set; }
        public string MusicUrl { get; set; }
        public string MusicAuthor { get; set; }
        public Nullable<System.DateTime> MusicCreateDate { get; set; }
        public string MusicImageUrl { get; set; }
        public string MusicDesciption { get; set; }
    }
}
