//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_ProjectInfo
    {
        public System.Guid ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<System.Guid> ProjectSource { get; set; }
        public string ProjectType { get; set; }
        public Nullable<System.Guid> ProjectTrackPhase { get; set; }
        public string ProjectLocation { get; set; }
        public string ProjectScale { get; set; }
        public Nullable<System.Guid> ProjectWay { get; set; }
        public Nullable<int> IsTender { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> ResponsibleID { get; set; }
        public string ProjectSourceOther { get; set; }
        public string ProjectTypeOther { get; set; }
        public string ApplyUser { get; set; }
        public Nullable<System.Guid> ApplyUserID { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string ImplementationName { get; set; }
        public string ConstructionUnits { get; set; }
        public string ConstructionUnitIDs { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DurationStart { get; set; }
        public Nullable<System.DateTime> DurationEnd { get; set; }
        public string Transfer { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ProjectRegistration { get; set; }
        public string ProjectManager { get; set; }
        public Nullable<System.Guid> ProjectManagerID { get; set; }
        public string Technical { get; set; }
        public Nullable<System.Guid> TechnicalID { get; set; }
        public Nullable<System.Guid> MainDeptID { get; set; }
        public string OtherDeptID { get; set; }
        public string MainDept { get; set; }
        public string OtherDept { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<System.Guid> ConfirmUserID { get; set; }
        public string ConfirmUserName { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<System.Guid> RemineUserID { get; set; }
        public string ProjectTypeName { get; set; }
        public string TransferName { get; set; }
    }
}
