//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Report
    {
        public int ReportId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> QuotedId { get; set; }
        public Nullable<int> CreateEmployee { get; set; }
        public Nullable<int> InviteEmployee { get; set; }
        public Nullable<int> OrderEmployee { get; set; }
        public Nullable<int> QuotedEmployee { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ComeDate { get; set; }
        public Nullable<System.DateTime> InviteLoseDate { get; set; }
        public Nullable<System.DateTime> OrderLoseDate { get; set; }
        public Nullable<int> CustomerState { get; set; }
        public Nullable<System.DateTime> OrderSuccessDate { get; set; }
    }
}
