//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserJurisdiction
    {
        public int JurisdictionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ChecksEmployee { get; set; }
        public Nullable<int> Dispatching { get; set; }
        public int DataPower { get; set; }
        public string DataPowerMd5Key { get; set; }
        public Nullable<bool> IsClose { get; set; }
    }
}
