//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using HHLWedding.DataAssmblly.CommonModel;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_LoginLog
    {
        [ExportAttr]
        [Display(Name = "登录编号")]
        public System.Guid LoginId { get; set; }
        [ExportAttr]
        [Display(Name = "登录名")]
        public Nullable<int> LoginEmployee { get; set; }
        [ExportAttr]
        [Display(Name = "登录日期")]
        public Nullable<System.DateTime> LoginDate { get; set; }
        [ExportAttr]
        [Display(Name = "登录城市")]
        public string LoginCity { get; set; }
        [ExportAttr]
        [Display(Name = "登录外网Ip")]
        public string LoginIpAddress { get; set; }
        [ExportAttr]
        [Display(Name = "登录内网Ip")]
        public string LoginInIp { get; set; }
        [ExportAttr]
        [Display(Name = "登录Key")]
        public string LoginEmployeeKey { get; set; }
    }
}
