//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Channel
    {
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public string ChannelAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Parent { get; set; }
        public string ChannelGetType { get; set; }
        public string StyleSheethem { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public string IndexCode { get; set; }
        public Nullable<int> SortInt { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Remark { get; set; }
    }
}
