//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_EmployeePower
    {
        public int PowerID { get; set; }
        public string Powername { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string UrlAddress { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
