//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHLWedding.DataAssmblly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Employee
    {
        public int EmployeeID { get; set; }
        public Nullable<int> JobID { get; set; }
        public int DepartmentID { get; set; }
        public int EmployeeTypeID { get; set; }
        public string EmployeeName { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ComeInDate { get; set; }
        public Nullable<bool> Sex { get; set; }
        public System.DateTime BornDate { get; set; }
        public string TelPhone { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
        public string ImageURL { get; set; }
        public string UploadImageName { get; set; }
        public string IdCard { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
    
        public virtual Sys_Department Sys_Department { get; set; }
        public virtual Sys_EmployeeJob Sys_EmployeeJob { get; set; }
        public virtual Sys_EmployeeType Sys_EmployeeType { get; set; }
    }
}
